services:
  - type: web
    name: housing-predict-service
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --timeout 120 backend.app:app
    envVars:
      - key: KAKAO_REST_API_KEY
        sync: false
